
package student;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentWS", targetNamespace = "http://student/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentWS {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "viewStudents", targetNamespace = "http://student/", className = "student.ViewStudents")
    @ResponseWrapper(localName = "viewStudentsResponse", targetNamespace = "http://student/", className = "student.ViewStudentsResponse")
    @Action(input = "http://student/StudentWS/viewStudentsRequest", output = "http://student/StudentWS/viewStudentsResponse")
    public String viewStudents();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://student/", className = "student.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://student/", className = "student.AddStudentResponse")
    @Action(input = "http://student/StudentWS/addStudentRequest", output = "http://student/StudentWS/addStudentResponse")
    public String addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://student/", className = "student.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://student/", className = "student.GetStudentResponse")
    @Action(input = "http://student/StudentWS/getStudentRequest", output = "http://student/StudentWS/getStudentResponse")
    public String getStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
