
package student;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentWSService", targetNamespace = "http://student/", wsdlLocation = "http://localhost:9098/student?wsdl")
public class StudentWSService
    extends Service
{

    private final static URL STUDENTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTWSSERVICE_EXCEPTION;
    private final static QName STUDENTWSSERVICE_QNAME = new QName("http://student/", "StudentWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9098/student?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTWSSERVICE_WSDL_LOCATION = url;
        STUDENTWSSERVICE_EXCEPTION = e;
    }

    public StudentWSService() {
        super(__getWsdlLocation(), STUDENTWSSERVICE_QNAME);
    }

    public StudentWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTWSSERVICE_QNAME, features);
    }

    public StudentWSService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTWSSERVICE_QNAME);
    }

    public StudentWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTWSSERVICE_QNAME, features);
    }

    public StudentWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentWS
     */
    @WebEndpoint(name = "StudentWSPort")
    public StudentWS getStudentWSPort() {
        return super.getPort(new QName("http://student/", "StudentWSPort"), StudentWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentWS
     */
    @WebEndpoint(name = "StudentWSPort")
    public StudentWS getStudentWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://student/", "StudentWSPort"), StudentWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTWSSERVICE_EXCEPTION!= null) {
            throw STUDENTWSSERVICE_EXCEPTION;
        }
        return STUDENTWSSERVICE_WSDL_LOCATION;
    }

}
