
package currency;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CurrencyWS", targetNamespace = "http://currency/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CurrencyWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertCurrency", targetNamespace = "http://currency/", className = "currency.ConvertCurrency")
    @ResponseWrapper(localName = "convertCurrencyResponse", targetNamespace = "http://currency/", className = "currency.ConvertCurrencyResponse")
    @Action(input = "http://currency/CurrencyWS/convertCurrencyRequest", output = "http://currency/CurrencyWS/convertCurrencyResponse")
    public double convertCurrency(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
