
package currency;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CurrencyWSService", targetNamespace = "http://currency/", wsdlLocation = "http://localhost:9095/currency?wsdl")
public class CurrencyWSService
    extends Service
{

    private final static URL CURRENCYWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CURRENCYWSSERVICE_EXCEPTION;
    private final static QName CURRENCYWSSERVICE_QNAME = new QName("http://currency/", "CurrencyWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9095/currency?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CURRENCYWSSERVICE_WSDL_LOCATION = url;
        CURRENCYWSSERVICE_EXCEPTION = e;
    }

    public CurrencyWSService() {
        super(__getWsdlLocation(), CURRENCYWSSERVICE_QNAME);
    }

    public CurrencyWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CURRENCYWSSERVICE_QNAME, features);
    }

    public CurrencyWSService(URL wsdlLocation) {
        super(wsdlLocation, CURRENCYWSSERVICE_QNAME);
    }

    public CurrencyWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CURRENCYWSSERVICE_QNAME, features);
    }

    public CurrencyWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrencyWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CurrencyWS
     */
    @WebEndpoint(name = "CurrencyWSPort")
    public CurrencyWS getCurrencyWSPort() {
        return super.getPort(new QName("http://currency/", "CurrencyWSPort"), CurrencyWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CurrencyWS
     */
    @WebEndpoint(name = "CurrencyWSPort")
    public CurrencyWS getCurrencyWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://currency/", "CurrencyWSPort"), CurrencyWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CURRENCYWSSERVICE_EXCEPTION!= null) {
            throw CURRENCYWSSERVICE_EXCEPTION;
        }
        return CURRENCYWSSERVICE_WSDL_LOCATION;
    }

}
