
package weather;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherWSService", targetNamespace = "http://weather/", wsdlLocation = "http://localhost:8888/weather?wsdl")
public class WeatherWSService
    extends Service
{

    private final static URL WEATHERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEATHERWSSERVICE_EXCEPTION;
    private final static QName WEATHERWSSERVICE_QNAME = new QName("http://weather/", "WeatherWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/weather?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERWSSERVICE_WSDL_LOCATION = url;
        WEATHERWSSERVICE_EXCEPTION = e;
    }

    public WeatherWSService() {
        super(__getWsdlLocation(), WEATHERWSSERVICE_QNAME);
    }

    public WeatherWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERWSSERVICE_QNAME, features);
    }

    public WeatherWSService(URL wsdlLocation) {
        super(wsdlLocation, WEATHERWSSERVICE_QNAME);
    }

    public WeatherWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERWSSERVICE_QNAME, features);
    }

    public WeatherWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherWS
     */
    @WebEndpoint(name = "WeatherWSPort")
    public WeatherWS getWeatherWSPort() {
        return super.getPort(new QName("http://weather/", "WeatherWSPort"), WeatherWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherWS
     */
    @WebEndpoint(name = "WeatherWSPort")
    public WeatherWS getWeatherWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://weather/", "WeatherWSPort"), WeatherWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERWSSERVICE_EXCEPTION!= null) {
            throw WEATHERWSSERVICE_EXCEPTION;
        }
        return WEATHERWSSERVICE_WSDL_LOCATION;
    }

}
