package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Monday, 11 May, 2026 12:32:50 AM IST
*/

public interface CalculatorOperations 
{
  double add (double a, double b);
  double subtract (double a, double b);
  double multiply (double a, double b);
  double divide (double a, double b);
} // interface CalculatorOperations
