
package todo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TodoWS", targetNamespace = "http://todo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TodoWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTask", targetNamespace = "http://todo/", className = "todo.AddTask")
    @ResponseWrapper(localName = "addTaskResponse", targetNamespace = "http://todo/", className = "todo.AddTaskResponse")
    @Action(input = "http://todo/TodoWS/addTaskRequest", output = "http://todo/TodoWS/addTaskResponse")
    public String addTask(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "viewTasks", targetNamespace = "http://todo/", className = "todo.ViewTasks")
    @ResponseWrapper(localName = "viewTasksResponse", targetNamespace = "http://todo/", className = "todo.ViewTasksResponse")
    @Action(input = "http://todo/TodoWS/viewTasksRequest", output = "http://todo/TodoWS/viewTasksResponse")
    public String viewTasks();

}
