
package todo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TodoWSService", targetNamespace = "http://todo/", wsdlLocation = "http://localhost:8088/todo?wsdl")
public class TodoWSService
    extends Service
{

    private final static URL TODOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException TODOWSSERVICE_EXCEPTION;
    private final static QName TODOWSSERVICE_QNAME = new QName("http://todo/", "TodoWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/todo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TODOWSSERVICE_WSDL_LOCATION = url;
        TODOWSSERVICE_EXCEPTION = e;
    }

    public TodoWSService() {
        super(__getWsdlLocation(), TODOWSSERVICE_QNAME);
    }

    public TodoWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TODOWSSERVICE_QNAME, features);
    }

    public TodoWSService(URL wsdlLocation) {
        super(wsdlLocation, TODOWSSERVICE_QNAME);
    }

    public TodoWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TODOWSSERVICE_QNAME, features);
    }

    public TodoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TodoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TodoWS
     */
    @WebEndpoint(name = "TodoWSPort")
    public TodoWS getTodoWSPort() {
        return super.getPort(new QName("http://todo/", "TodoWSPort"), TodoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TodoWS
     */
    @WebEndpoint(name = "TodoWSPort")
    public TodoWS getTodoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://todo/", "TodoWSPort"), TodoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TODOWSSERVICE_EXCEPTION!= null) {
            throw TODOWSSERVICE_EXCEPTION;
        }
        return TODOWSSERVICE_WSDL_LOCATION;
    }

}
