package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Wednesday, 22 April, 2026 11:22:22 PM IST
*/

public interface CalculatorOperations 
{
  double add (double a, double b);
  double subtract (double a, double b);
  double multiply (double a, double b);
  double divide (double a, double b);
} // interface CalculatorOperations
